[package]
name = "fuzz"
version = "0.1.0"
edition = "2024"

[dependencies]
afl = "0.17"
anyhow = "1.0"
blockwatch = { path = ".." }
regex = "1.12.2"

[[bin]]
name = "parser_fuzz"
path = "src/parser_fuzz.rs"
